CREATE TABLE IF NOT EXISTS users (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    roomid UUID NOT NULL UNIQUE,
    username VARCHAR(55) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL
);
