CREATE SCHEMA IF NOT EXISTS auth;

CREATE TABLE IF NOT EXISTS auth.techroom (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    roomid UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    username VARCHAR(55) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL
);
